=== djo316/survival-magick/Survival_Magick/WebContent/XMLS/blog.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">


	<!-- Élément simple,ce qui compose un articles -->
	<xs:element name="titre" type="xs:string" />
	<xs:element name="auteur" type="xs:string" />
	<xs:element name="dateCreation" type="xs:date" />
	<xs:element name="derniereModification" type="xs:date" />
	<xs:element name="lienImage" type="xs:string" />
	<xs:element name="article">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:whiteSpace value="preserve" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<!-- Attribut, comment on classe les articles -->
	<xs:attribute name="categorie" type="xs:string" />
	<xs:attribute name="billetID" type="xs:integer" />

	<!-- Élément complexes, la construction des articles -->
	<xs:element name="billet">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="titre" />
				<xs:element ref="auteur" />
				<xs:element ref="dateCreation" />
				<xs:element ref="derniereModification" minOccurs="0" />
				<xs:element ref="article" />
				<xs:element ref="lienImage" minOccurs="0" />
			</xs:sequence>
			<xs:attribute ref="categorie" use="required" />
			<xs:attribute ref="billetID" use="required" />
		</xs:complexType>
	</xs:element>



	<xs:element name="blog">
		<xs:complexType mixed="true">
			<xs:sequence>
				<xs:element ref="billet" maxOccurs="unbounded">
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== djo316/survival-magick/Survival_Magick/WebContent/XML/blog 2.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../XSL/blog.xsl"?>
<blog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../XMLS/blog.xsd">
	<billet billetID="1" categorie="">
		<titre>Premier article</titre>
		<auteur>Lorem Ipsum</auteur>
		<dateCreation>2018-06-18</dateCreation>
		<article>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</article>
		<lienImage>../IMG/banner820x312.jpg</lienImage>
	</billet>
	<billet billetID="2" categorie="">
		<titre>Deuxieme article</titre>
		<auteur>Lorem Ipsum</auteur>
		<dateCreation>2018-06-18</dateCreation>
		<derniereModification>2018-06-18</derniereModification>
		<article>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</article>
	</billet>
</blog>
